"""keys and triggers.

Revision ID: 02b93897c8e3
Revises: b0423db9f1e9
Create Date: 2023-02-17 08:26:21.801975
"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "02b93897c8e3"  # pragma: allowlist secret
down_revision = "b0423db9f1e9"  # pragma: allowlist secret
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "account_validations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("account_id", sa.Integer(), nullable=False),
        sa.Column("validation_key", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["accounts.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_account_validations_account_id"), "account_validations", ["account_id"], unique=True)
    op.create_index(op.f("ix_account_validations_id"), "account_validations", ["id"], unique=False)

    # Create the delete_expired_account_validations() function
    op.execute(
        """
        CREATE OR REPLACE FUNCTION delete_expired_account_validations()
        RETURNS TRIGGER AS $$
        BEGIN
            DELETE FROM account_validations WHERE created_at < NOW() - INTERVAL '5 minutes';
            RETURN NEW;
        END;
        $$ LANGUAGE plpgsql;
    """
    )

    # Create the delete_expired_account_validations_trigger trigger
    op.execute(
        """
        CREATE TRIGGER delete_expired_account_validations_trigger
        BEFORE INSERT ON account_validations
        FOR EACH ROW
        EXECUTE FUNCTION delete_expired_account_validations();
    """
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        """
        DROP TRIGGER delete_expired_account_validations_trigger ON account_validations;
    """
    )
    op.execute("DROP FUNCTION delete_expired_account_validations();")

    op.drop_index(op.f("ix_account_validations_id"), table_name="account_validations")
    op.drop_index(op.f("ix_account_validations_account_id"), table_name="account_validations")
    op.drop_table("account_validations")
    # ### end Alembic commands ###
