"""is active.

Revision ID: c1f00f1b80e9
Revises: b68f620c315a
Create Date: 2022-10-06 20:02:29.958018
"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "c1f00f1b80e9"
down_revision = "b68f620c315a"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("is_active", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "is_active")
    # ### end Alembic commands ###
